### ISSUE TITLE
Accommodation and Meals should be pre-selected

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#2]

**Comment by afhill** [comment]
Meals: 


breakfast
Yukon   22.75
NWT       24.15
Nunavut  27.35
Rest of Canada: 20.35

Lunch
Yukon   20.90
NWT   29.30
Nunavut  33.20
Rest of Canada: 20.60

Dinner
Yukon  60.25
NWT: 62.70
Nunavut: 88.45
Rest of Canda: 50.55 

Incidentals
All of Canada $17.30

**Comment by potatowave** [comment]
Done.
