### ISSUE TITLE
Calendar updates

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#25]
* Is it possible to introduce range selection, like Airbnb?
* At the very least, default the "returning" date to the "starting" date.

Airbnb:
![Screen Shot 2019-12-13 at 2 53 58 PM](https://user-images.githubusercontent.com/3179624/70828589-a6093d00-1db9-11ea-953e-c926c7d71c75.png)

**Comment by potatowave** [comment]
Added on staging, closing issue.
