### ISSUE TITLE
Add $150 (or so) field for change fees

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#38]
*Idea, needs discussion*

This idea came up during our Wednesday offsite work session. Idea is to add a field for change fees in the estimator. Maybe this fits somewhere else, or can be optional. Don't want to bloat the estimator, but wanted to log it!

**Comment by potatowave** [comment]
Needs further discussion. 

Including threshold might be a good platform feature! (per department preference?)
