### ISSUE TITLE
Bring rental car rates into the estimator

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#39]
For example, Ottawa's rates are: https://rehelv-acrd.tpsgc-pwgsc.gc.ca/ACRDS/rechercher-search-5-eng.aspx?p=0&c=398&s=R&u=1&t=C&l=X

Search for all rates (in Canada) here: https://rehelv-acrd.tpsgc-pwgsc.gc.ca/acrds/rechercher-search-4-eng.aspx

Per Andrea: "Ripe for an API!"

**Comment by mkewins** [comment]
<img width="734" alt="Screen Shot 2020-01-02 at 8 20 33 AM" src="https://user-images.githubusercontent.com/3179624/71835377-657ea580-307f-11ea-97bd-aad40d610b25.png">

**Comment by potatowave** [comment]
Adding to backlog, closing issue until we revisit this.
