### ISSUE TITLE
Render calendar from Sunday–Saturday

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#42]

**Comment by potatowave** [comment]
@mkewins Is the a "why" here beyond a users preference?

A lot of calendar apps have this as a preference rather than a hard setting.

**Comment by mkewins** [comment]
The default Outlook calendar is from Sunday–Saturday, I'm guessing this is what most public servants see on a daily basis (I can do a quick poll of 5 people on our office floor too :)). It took someone off guard seeing the week start on Monday. Also, Airbnb, Google Calendar start on Sunday.

**Comment by potatowave** [comment]
On staging.
