### ISSUE TITLE
Mileage/taxi estimates based on starting and destination address

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#43]
Original: https://trello.com/c/3UUxrJHU/1-mileage-taxi-estimates-based-on-starting-and-destination-address

**Comment by mkewins** [comment]
Candidate for standalone widget that we can link to from estimator?

**Comment by potatowave** [comment]
- Remove Ground Transportation category
- Taxi as its own category
- Add personal vehicle (x km's registered in select(province)) as its own category
- Car Rental as its own category
- Parking as its own category

**Comment by potatowave** [comment]
This issue is going to be addressed in the new repo, https://github.com/nextgentravel/travel-estimator-simple/ as its first issue, to become the 'simple' version of the estimator. 

https://github.com/nextgentravel/travel-estimator-simple/issues/1
