### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#47]
* Change copy from "Your name" to "Traveller's name"
* Instead of "Itemize" beside ground transportation, change button text to "Help me estimate this"
* From Jan 8–10, remove hardcoded values from ground transportation itemized modal (so we can see how users react to no anchored/suggested values)
* Revert copy from "When you get there, how are you getting around?" to "Ground transportation"

**Comment by potatowave** [comment]
Merged intro Staging.
