### ISSUE TITLE
(Bug, Chrome, Master) Hitting back button from print page goes back to first page of form (start/end/dates)

### ISSUE THREAD

**Issue by mkewins** [nextgentravel/travel-estimator#50]

**Comment by potatowave** [comment]
This can be replicated by clicking the "Itemize" or "Select meals to include" link that opens the modal, you'll notice that in the URL bar the URL will lose the `/calculate` route.  Need to figure out a way to prevent this.

**Comment by potatowave** [comment]
Fixed on staging.
